### ISSUE TITLE
Nepotreban observer

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#10]
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/displaying_yamb_ticket/FragmentYamb/FragmentYambTicket.kt#L51

Koji je benefit ove pretplate? View sluša viewmodel event da bi viewmodelu javio da se nešto desilo?

Ukloniti iz VM-a nepotrebne pretplate:
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/displaying_yamb_ticket/FragmentYamb/ViewModelFragmentYambTicket.kt#L29

**Comment by DavorStajcer** [comment]
Popravio sam oba segmenta.
