### ISSUE TITLE
Obrazloži namjernu klase

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#12]
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/displaying_yamb_ticket/FragmentYamb/ItemListAndStatsGenerator.kt#L11

Pojasni način na koji koristiš klasu. 
Koji je benefit da imaš privatne varijable u njoj?

**Comment by DavorStajcer** [comment]
Klasa mi služi za modificiranje liste itema za prikaz u recycleru nakon određene interakcije korisnika sa aplikacijom (npr. kda se unese nova vrijednost u yamb listić, treba mi nova lista u kojoj je unešena vrijednost kliknutog itema i onemogućen je klik na iteme, kada rolam sve omogućava mi se unos nove vriejdnosti na ticket , tj. treba mi nova lista koja mi da je mogućnost da mi određeni itemi budu klikabilni).
