### ISSUE TITLE
Ujednačiti nazive direktorija

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#2]
Trenutno u aplikaciji postoje nazivi displaying_yamb_ticket te savedGames. 

- [ ] odlučiti se za naming - snake case ili cammel case te implementirati izmjenu    Preporuka snake case, pošto se on koristi kod resurs foldera. Imena klasa trebaju biti cammelCase.
- [] prepraviti nazive klasa - trenutno se u folderu changing_fragments/ nalazi main activity. Prema ovome bi se main activity trebao zvato changingFragmentsActivity (predlažem da se definira novo ime) . Proći kroz cijeli projekt i popraviti ovakve probleme.
- [] prepraviti varijable. Varijable trebaju biti pisane cammel case-om : https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/res/layout/fragment_cubes.xml#L6 

- [] Ujednačiti nazive klasa - malo se zovu FunkcionalnostTipArhitetkure, malo se zovu TipArhitektureFunckionalnost. 
https://github.com/DavorStajcer/FactoryAssignments/blob/master/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/displaying_yamb_ticket/FragmentYamb/ViewModelFragmentYambTicket.kt#L24
Prijedlog: neka zovu prema TipFunkcionalnostiTipArhitekture.

**Comment by DavorStajcer** [comment]
Prepravio osam sva imena varijabli na cammel case, te sam imena klasa prepravio na TipFunkcionalnostiTipArhitekture (npr. RollingCubesViewModel)
