### ISSUE TITLE
Podaci se nalazi u view-u

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#3]
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/changing_fragments/MainActivity.kt#L22

Podaci se drže na view strani. Ne koristiti HC-ane stringove. Stringovi se trebaju povući iz resursa.

**Comment by DavorStajcer** [comment]
Maknuo sam u viewModel.
