### ISSUE TITLE
Main Activity poslovna logika

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#4]
Koji je benefit da main activity zna nešto o poslovnoj logici kockica? Kako on koristi taj podatak za odlučivanje prikaza screena?
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/changing_fragments/MainAcitivtyViewModel.kt#L18

**Comment by DavorStajcer** [comment]
Označeni kod mi služi za postavljanje prvobitnog stanja rolanih kockica i klikabilnosti yamb ticketa. Maknuo sam taj dio koda kod inicijalizacije view modela rolanja kockica.
