### ISSUE TITLE
Opcionalni adapter

### ISSUE THREAD

**Issue by matijasolic** [DavorStajcer/FactoryAssignments#8]
https://github.com/DavorStajcer/FactoryAssignments/blob/515f35fa57f5731e1a5292f22e159318f670c538/app/src/main/java/com/example/autofillgridlayoutmanagerapplication/displaying_yamb_ticket/FragmentYamb/FragmentYambTicket.kt#L28

Zašto je adapter opcionalan kada ti je on uvijek potreban?

**Comment by DavorStajcer** [comment]
Popravio.
